//
// This file is automatically generated by scripts/generate-plugins.go -- Do not edit!
//

package command

import (
	"fmt"
	"log"
	"regexp"
	"strings"

	packersdk "github.com/Bourne-ID/packer/packer-plugin-sdk/packer"
	"github.com/Bourne-ID/packer/packer-plugin-sdk/plugin"

	alicloudecsbuilder "github.com/Bourne-ID/packer/builder/alicloud/ecs"
	amazonchrootbuilder "github.com/Bourne-ID/packer/builder/amazon/chroot"
	amazonebsbuilder "github.com/Bourne-ID/packer/builder/amazon/ebs"
	amazonebssurrogatebuilder "github.com/Bourne-ID/packer/builder/amazon/ebssurrogate"
	amazonebsvolumebuilder "github.com/Bourne-ID/packer/builder/amazon/ebsvolume"
	amazoninstancebuilder "github.com/Bourne-ID/packer/builder/amazon/instance"
	azurearmbuilder "github.com/Bourne-ID/packer/builder/azure/arm"
	azurechrootbuilder "github.com/Bourne-ID/packer/builder/azure/chroot"
	azuredtlbuilder "github.com/Bourne-ID/packer/builder/azure/dtl"
	cloudstackbuilder "github.com/Bourne-ID/packer/builder/cloudstack"
	digitaloceanbuilder "github.com/Bourne-ID/packer/builder/digitalocean"
	dockerbuilder "github.com/Bourne-ID/packer/builder/docker"
	filebuilder "github.com/Bourne-ID/packer/builder/file"
	googlecomputebuilder "github.com/Bourne-ID/packer/builder/googlecompute"
	hcloudbuilder "github.com/Bourne-ID/packer/builder/hcloud"
	hyperonebuilder "github.com/Bourne-ID/packer/builder/hyperone"
	hypervisobuilder "github.com/Bourne-ID/packer/builder/hyperv/iso"
	hypervvmcxbuilder "github.com/Bourne-ID/packer/builder/hyperv/vmcx"
	jdcloudbuilder "github.com/Bourne-ID/packer/builder/jdcloud"
	linodebuilder "github.com/Bourne-ID/packer/builder/linode"
	lxcbuilder "github.com/Bourne-ID/packer/builder/lxc"
	lxdbuilder "github.com/Bourne-ID/packer/builder/lxd"
	ncloudbuilder "github.com/Bourne-ID/packer/builder/ncloud"
	nullbuilder "github.com/Bourne-ID/packer/builder/null"
	oneandonebuilder "github.com/Bourne-ID/packer/builder/oneandone"
	openstackbuilder "github.com/Bourne-ID/packer/builder/openstack"
	oracleclassicbuilder "github.com/Bourne-ID/packer/builder/oracle/classic"
	oracleocibuilder "github.com/Bourne-ID/packer/builder/oracle/oci"
	oscbsubuilder "github.com/Bourne-ID/packer/builder/osc/bsu"
	oscbsusurrogatebuilder "github.com/Bourne-ID/packer/builder/osc/bsusurrogate"
	oscbsuvolumebuilder "github.com/Bourne-ID/packer/builder/osc/bsuvolume"
	oscchrootbuilder "github.com/Bourne-ID/packer/builder/osc/chroot"
	parallelsisobuilder "github.com/Bourne-ID/packer/builder/parallels/iso"
	parallelspvmbuilder "github.com/Bourne-ID/packer/builder/parallels/pvm"
	profitbricksbuilder "github.com/Bourne-ID/packer/builder/profitbricks"
	proxmoxbuilder "github.com/Bourne-ID/packer/builder/proxmox"
	proxmoxclonebuilder "github.com/Bourne-ID/packer/builder/proxmox/clone"
	proxmoxisobuilder "github.com/Bourne-ID/packer/builder/proxmox/iso"
	qemubuilder "github.com/Bourne-ID/packer/builder/qemu"
	scalewaybuilder "github.com/Bourne-ID/packer/builder/scaleway"
	tencentcloudcvmbuilder "github.com/Bourne-ID/packer/builder/tencentcloud/cvm"
	tritonbuilder "github.com/Bourne-ID/packer/builder/triton"
	uclouduhostbuilder "github.com/Bourne-ID/packer/builder/ucloud/uhost"
	vagrantbuilder "github.com/Bourne-ID/packer/builder/vagrant"
	virtualboxisobuilder "github.com/Bourne-ID/packer/builder/virtualbox/iso"
	virtualboxovfbuilder "github.com/Bourne-ID/packer/builder/virtualbox/ovf"
	virtualboxvmbuilder "github.com/Bourne-ID/packer/builder/virtualbox/vm"
	vmwareisobuilder "github.com/Bourne-ID/packer/builder/vmware/iso"
	vmwarevmxbuilder "github.com/Bourne-ID/packer/builder/vmware/vmx"
	vsphereclonebuilder "github.com/Bourne-ID/packer/builder/vsphere/clone"
	vsphereisobuilder "github.com/Bourne-ID/packer/builder/vsphere/iso"
	yandexbuilder "github.com/Bourne-ID/packer/builder/yandex"
	alicloudimportpostprocessor "github.com/Bourne-ID/packer/post-processor/alicloud-import"
	amazonimportpostprocessor "github.com/Bourne-ID/packer/post-processor/amazon-import"
	artificepostprocessor "github.com/Bourne-ID/packer/post-processor/artifice"
	checksumpostprocessor "github.com/Bourne-ID/packer/post-processor/checksum"
	compresspostprocessor "github.com/Bourne-ID/packer/post-processor/compress"
	digitaloceanimportpostprocessor "github.com/Bourne-ID/packer/post-processor/digitalocean-import"
	dockerimportpostprocessor "github.com/Bourne-ID/packer/post-processor/docker-import"
	dockerpushpostprocessor "github.com/Bourne-ID/packer/post-processor/docker-push"
	dockersavepostprocessor "github.com/Bourne-ID/packer/post-processor/docker-save"
	dockertagpostprocessor "github.com/Bourne-ID/packer/post-processor/docker-tag"
	exoscaleimportpostprocessor "github.com/Bourne-ID/packer/post-processor/exoscale-import"
	googlecomputeexportpostprocessor "github.com/Bourne-ID/packer/post-processor/googlecompute-export"
	googlecomputeimportpostprocessor "github.com/Bourne-ID/packer/post-processor/googlecompute-import"
	manifestpostprocessor "github.com/Bourne-ID/packer/post-processor/manifest"
	shelllocalpostprocessor "github.com/Bourne-ID/packer/post-processor/shell-local"
	ucloudimportpostprocessor "github.com/Bourne-ID/packer/post-processor/ucloud-import"
	vagrantpostprocessor "github.com/Bourne-ID/packer/post-processor/vagrant"
	vagrantcloudpostprocessor "github.com/Bourne-ID/packer/post-processor/vagrant-cloud"
	vspherepostprocessor "github.com/Bourne-ID/packer/post-processor/vsphere"
	vspheretemplatepostprocessor "github.com/Bourne-ID/packer/post-processor/vsphere-template"
	yandexexportpostprocessor "github.com/Bourne-ID/packer/post-processor/yandex-export"
	yandeximportpostprocessor "github.com/Bourne-ID/packer/post-processor/yandex-import"
	ansibleprovisioner "github.com/Bourne-ID/packer/provisioner/ansible"
	ansiblelocalprovisioner "github.com/Bourne-ID/packer/provisioner/ansible-local"
	azuredtlartifactprovisioner "github.com/Bourne-ID/packer/provisioner/azure-dtlartifact"
	breakpointprovisioner "github.com/Bourne-ID/packer/provisioner/breakpoint"
	chefclientprovisioner "github.com/Bourne-ID/packer/provisioner/chef-client"
	chefsoloprovisioner "github.com/Bourne-ID/packer/provisioner/chef-solo"
	convergeprovisioner "github.com/Bourne-ID/packer/provisioner/converge"
	fileprovisioner "github.com/Bourne-ID/packer/provisioner/file"
	inspecprovisioner "github.com/Bourne-ID/packer/provisioner/inspec"
	powershellprovisioner "github.com/Bourne-ID/packer/provisioner/powershell"
	puppetmasterlessprovisioner "github.com/Bourne-ID/packer/provisioner/puppet-masterless"
	puppetserverprovisioner "github.com/Bourne-ID/packer/provisioner/puppet-server"
	saltmasterlessprovisioner "github.com/Bourne-ID/packer/provisioner/salt-masterless"
	shellprovisioner "github.com/Bourne-ID/packer/provisioner/shell"
	shelllocalprovisioner "github.com/Bourne-ID/packer/provisioner/shell-local"
	sleepprovisioner "github.com/Bourne-ID/packer/provisioner/sleep"
	windowsrestartprovisioner "github.com/Bourne-ID/packer/provisioner/windows-restart"
	windowsshellprovisioner "github.com/Bourne-ID/packer/provisioner/windows-shell"
)

type PluginCommand struct {
	Meta
}

var Builders = map[string]packersdk.Builder{
	"alicloud-ecs":        new(alicloudecsbuilder.Builder),
	"amazon-chroot":       new(amazonchrootbuilder.Builder),
	"amazon-ebs":          new(amazonebsbuilder.Builder),
	"amazon-ebssurrogate": new(amazonebssurrogatebuilder.Builder),
	"amazon-ebsvolume":    new(amazonebsvolumebuilder.Builder),
	"amazon-instance":     new(amazoninstancebuilder.Builder),
	"azure-arm":           new(azurearmbuilder.Builder),
	"azure-chroot":        new(azurechrootbuilder.Builder),
	"azure-dtl":           new(azuredtlbuilder.Builder),
	"cloudstack":          new(cloudstackbuilder.Builder),
	"digitalocean":        new(digitaloceanbuilder.Builder),
	"docker":              new(dockerbuilder.Builder),
	"file":                new(filebuilder.Builder),
	"googlecompute":       new(googlecomputebuilder.Builder),
	"hcloud":              new(hcloudbuilder.Builder),
	"hyperone":            new(hyperonebuilder.Builder),
	"hyperv-iso":          new(hypervisobuilder.Builder),
	"hyperv-vmcx":         new(hypervvmcxbuilder.Builder),
	"jdcloud":             new(jdcloudbuilder.Builder),
	"linode":              new(linodebuilder.Builder),
	"lxc":                 new(lxcbuilder.Builder),
	"lxd":                 new(lxdbuilder.Builder),
	"ncloud":              new(ncloudbuilder.Builder),
	"null":                new(nullbuilder.Builder),
	"oneandone":           new(oneandonebuilder.Builder),
	"openstack":           new(openstackbuilder.Builder),
	"oracle-classic":      new(oracleclassicbuilder.Builder),
	"oracle-oci":          new(oracleocibuilder.Builder),
	"osc-bsu":             new(oscbsubuilder.Builder),
	"osc-bsusurrogate":    new(oscbsusurrogatebuilder.Builder),
	"osc-bsuvolume":       new(oscbsuvolumebuilder.Builder),
	"osc-chroot":          new(oscchrootbuilder.Builder),
	"parallels-iso":       new(parallelsisobuilder.Builder),
	"parallels-pvm":       new(parallelspvmbuilder.Builder),
	"profitbricks":        new(profitbricksbuilder.Builder),
	"proxmox":             new(proxmoxbuilder.Builder),
	"proxmox-clone":       new(proxmoxclonebuilder.Builder),
	"proxmox-iso":         new(proxmoxisobuilder.Builder),
	"qemu":                new(qemubuilder.Builder),
	"scaleway":            new(scalewaybuilder.Builder),
	"tencentcloud-cvm":    new(tencentcloudcvmbuilder.Builder),
	"triton":              new(tritonbuilder.Builder),
	"ucloud-uhost":        new(uclouduhostbuilder.Builder),
	"vagrant":             new(vagrantbuilder.Builder),
	"virtualbox-iso":      new(virtualboxisobuilder.Builder),
	"virtualbox-ovf":      new(virtualboxovfbuilder.Builder),
	"virtualbox-vm":       new(virtualboxvmbuilder.Builder),
	"vmware-iso":          new(vmwareisobuilder.Builder),
	"vmware-vmx":          new(vmwarevmxbuilder.Builder),
	"vsphere-clone":       new(vsphereclonebuilder.Builder),
	"vsphere-iso":         new(vsphereisobuilder.Builder),
	"yandex":              new(yandexbuilder.Builder),
}

var Provisioners = map[string]packersdk.Provisioner{
	"ansible":           new(ansibleprovisioner.Provisioner),
	"ansible-local":     new(ansiblelocalprovisioner.Provisioner),
	"azure-dtlartifact": new(azuredtlartifactprovisioner.Provisioner),
	"breakpoint":        new(breakpointprovisioner.Provisioner),
	"chef-client":       new(chefclientprovisioner.Provisioner),
	"chef-solo":         new(chefsoloprovisioner.Provisioner),
	"converge":          new(convergeprovisioner.Provisioner),
	"file":              new(fileprovisioner.Provisioner),
	"inspec":            new(inspecprovisioner.Provisioner),
	"powershell":        new(powershellprovisioner.Provisioner),
	"puppet-masterless": new(puppetmasterlessprovisioner.Provisioner),
	"puppet-server":     new(puppetserverprovisioner.Provisioner),
	"salt-masterless":   new(saltmasterlessprovisioner.Provisioner),
	"shell":             new(shellprovisioner.Provisioner),
	"shell-local":       new(shelllocalprovisioner.Provisioner),
	"sleep":             new(sleepprovisioner.Provisioner),
	"windows-restart":   new(windowsrestartprovisioner.Provisioner),
	"windows-shell":     new(windowsshellprovisioner.Provisioner),
}

var PostProcessors = map[string]packersdk.PostProcessor{
	"alicloud-import":      new(alicloudimportpostprocessor.PostProcessor),
	"amazon-import":        new(amazonimportpostprocessor.PostProcessor),
	"artifice":             new(artificepostprocessor.PostProcessor),
	"checksum":             new(checksumpostprocessor.PostProcessor),
	"compress":             new(compresspostprocessor.PostProcessor),
	"digitalocean-import":  new(digitaloceanimportpostprocessor.PostProcessor),
	"docker-import":        new(dockerimportpostprocessor.PostProcessor),
	"docker-push":          new(dockerpushpostprocessor.PostProcessor),
	"docker-save":          new(dockersavepostprocessor.PostProcessor),
	"docker-tag":           new(dockertagpostprocessor.PostProcessor),
	"exoscale-import":      new(exoscaleimportpostprocessor.PostProcessor),
	"googlecompute-export": new(googlecomputeexportpostprocessor.PostProcessor),
	"googlecompute-import": new(googlecomputeimportpostprocessor.PostProcessor),
	"manifest":             new(manifestpostprocessor.PostProcessor),
	"shell-local":          new(shelllocalpostprocessor.PostProcessor),
	"ucloud-import":        new(ucloudimportpostprocessor.PostProcessor),
	"vagrant":              new(vagrantpostprocessor.PostProcessor),
	"vagrant-cloud":        new(vagrantcloudpostprocessor.PostProcessor),
	"vsphere":              new(vspherepostprocessor.PostProcessor),
	"vsphere-template":     new(vspheretemplatepostprocessor.PostProcessor),
	"yandex-export":        new(yandexexportpostprocessor.PostProcessor),
	"yandex-import":        new(yandeximportpostprocessor.PostProcessor),
}

var pluginRegexp = regexp.MustCompile("packer-(builder|post-processor|provisioner)-(.+)")

func (c *PluginCommand) Run(args []string) int {
	// This is an internal call (users should not call this directly) so we're
	// not going to do much input validation. If there's a problem we'll often
	// just crash. Error handling should be added to facilitate debugging.
	log.Printf("args: %#v", args)
	if len(args) != 1 {
		c.Ui.Error("Wrong number of args")
		return 1
	}

	// Plugin will match something like "packer-builder-amazon-ebs"
	parts := pluginRegexp.FindStringSubmatch(args[0])
	if len(parts) != 3 {
		c.Ui.Error(fmt.Sprintf("Error parsing plugin argument [DEBUG]: %#v", parts))
		return 1
	}
	pluginType := parts[1] // capture group 1 (builder|post-processor|provisioner)
	pluginName := parts[2] // capture group 2 (.+)

	server, err := plugin.Server()
	if err != nil {
		c.Ui.Error(fmt.Sprintf("Error starting plugin server: %s", err))
		return 1
	}

	switch pluginType {
	case "builder":
		builder, found := Builders[pluginName]
		if !found {
			c.Ui.Error(fmt.Sprintf("Could not load builder: %s", pluginName))
			return 1
		}
		server.RegisterBuilder(builder)
	case "provisioner":
		provisioner, found := Provisioners[pluginName]
		if !found {
			c.Ui.Error(fmt.Sprintf("Could not load provisioner: %s", pluginName))
			return 1
		}
		server.RegisterProvisioner(provisioner)
	case "post-processor":
		postProcessor, found := PostProcessors[pluginName]
		if !found {
			c.Ui.Error(fmt.Sprintf("Could not load post-processor: %s", pluginName))
			return 1
		}
		server.RegisterPostProcessor(postProcessor)
	}

	server.Serve()

	return 0
}

func (*PluginCommand) Help() string {
	helpText := `
Usage: packer plugin PLUGIN

  Runs an internally-compiled version of a plugin from the packer binary.

  NOTE: this is an internal command and you should not call it yourself.
`

	return strings.TrimSpace(helpText)
}

func (c *PluginCommand) Synopsis() string {
	return "internal plugin command"
}
